---
title: '4,222 Introduction to Programming'
subtitle: 'Exercise Week 2: First commands in `git`'
author: "Aurélien Sallin, Lea Tschan, Valentina Sontheim"
date: "2025-02-27"
code-line-numbers: false
format:
  html:
    # template-partials:
      #  - ../../style/title-slide.html
    smaller: true
    embed-resources: true
    self-contained: true
    slide-number: c
    theme: ../../assets/style/hsgtheme.scss
highlight-style: dracula
cache: false
echo: false
execute:
  echo: true
---

**in construction!!**


## Install `git` and the VSCode extension `Git Graph`

**This step has to be done before the exercise session.** Please follow the instructions on the git website: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

For Windows users, we recommend installing git via the Git for Windows installer: https://git-scm.com/download/win. For Mac users, git is often already installed. On Mavericks (10.9) or above you can do this simply by trying to run git from the Terminal the very first time.

```bash
$ git --version
```

If you don’t have it installed already, it will prompt you to install it. If you want a more up to date version, you can also install it via a binary installer. A macOS Git installer is maintained and available for download at the Git website, at https://git-scm.com/download/mac.

If you haven't done it from the course, download the [Git Cheat Sheet](https://education.github.com/git-cheat-sheet-education.pdf) and save it in /week02

<br>

## Configurate git on your machine

Follow the step here to configurate your git installation.

```bash
# Add your name
git config --global user.name "Your Name"

# Add your email address
git config --global user.email "your.email@unisg.ch"

# Use modern main branch name
git config --global init.defaultbranch main
```

```bash
# For Linux/Mac:
git config --global core.autocrlf input

# For Windows:
git config --global core.autocrlf true
```


<br>

## Initialize a `git` repository

We will work with our folder structure:

```
Introduction_to_programming/
├── github_course_materials/ # is empty for now, you will clone the git repo in week 3
├── exercises/               # Student's own work
│   ├── week_01/
│   ├── week_02/
│   ├── ...
│   ├── week_12/
├── group_project/
│   ├── ...
```

1. Identify the filepath of the directory Introduction_to_programming/exercises/week_02.
2. In the terminal, navigate to the directory.
3. There, initialize a git repository using `git init`. Check your git repo using `git status`.

::: {.callout-tip collapse="true"}
#### Solution
In your terminal from VSCode, navigate to your cd Introduction_to_programming/exercises/week_02. Then:

```bash
git init
# Initialized empty Git repository in /Users/Introduction_to_programming/exercises/week_02
```
:::

<br>

## First tracking and commit

1. In `week_02`, create a text file named `humorforprogrammers.txt` containing the sentence "*Code is like humor. When you have to explain it, it’s bad.*" using your terminal or simply using VSCode (new file -> save)
2. Observe what happens with `git status`. Check `git log`.
3. Add the file to the staging area. Check with `git status`.
4. Create your first commit. Commit the new file with the commit message "text file created". Check with `git status`.
5. Change the text in `humorforprogrammers.txt` to "*Code is absolutely not like humor.*" and save. Use `git diff` to see the actual unstaged changes.
6. Add the file to the staging area and commit the new file with the commit message "text file modified because disagreement".  Check with `git status` and with `git log`.
7. Look at your sidebar in VSCode. You'll notice the `git` GUI. Now create a new file `hello.txt` containing "hello world!". Observe the sidebar. Using the GUI, add `hello.txt` and commit, using a nice commit message.


::: {.callout-tip collapse="true"}
#### Solution

```bash
#| eval = false
echo "Code is like humor. When you have to explain it, it’s bad." > humorforprogrammers.txt

# verify
cat humorforprogrammers.txt
```

```bash
git add humorforprogrammers.txt
git status
git commit -m "text file created"
```

```bash
echo "*Code is absolutely not like humor.*" > humorforprogrammers.txt
```

```bash
git add humorforprogrammers.txt
git status
git commit -m "text file modified because disagreement"
```

Then use the GUI to add and commit `hello.txt` with a nice commit message.
:::


<br>

## Ignore some files

1. Navigate to your repo `/week_02` in exercises.
2. If you haven't done it from the course, download the [Git Cheat Sheet](https://education.github.com/git-cheat-sheet-education.pdf) and save it in `/week_02`
2. Create a new .gitignore file to ignore only this cheatsheet.
5. Add all the files to your repo and commit. Notice what's happening.
6. Change the .gitignore file to the following file. Explain what the new .gitignore file does. Commit.

```bash
# Data and generated outputs
*.csv
*.tsv
*.xlsx
*.pdf
*.png
*.jpg
*.html

# Python
__pycache__/
*.pyc

# Virtual environment (uv)
.venv/

# Editor / OS files
.DS_Store # typical for macOS!
.vscode/
```

<br>

## Time-Travel ⏱️

- Go back to your directory `/week_02` in exercises.
- Open the git log of your respository or call it with `git log`. From the log, identify the commit hash (identifier) of your first commit. Note that `HEAD` is used to reference commits relatively, with `HEAD` being the current commit, `HEAD~1` the previous commit, `HEAD~2` the commit two commits ago, and so on.
- Checkout the previous commit using the `git checkout` function. As seen in the course, you can checkout to a git commit using the commit identifier. Or, you can use the following syntax: `checkout HEAD~1`.
- Go back to your main branch using `git checkout`.

::: {.callout-tip collapse="true"}
#### Solution
Please complete. Make sure you are ready to explain what a detached head is and how to get back to the main branch.
:::


<br>

## On 🪵, 🌲

- Navigate to your repo in `/week_02` in exercises.
- Create a new branch called `fixCode`. Checkout the new branch. Make sure you're on the right branch using `git status`. Check the different branches of your repo with `git branch`.
- Add a new file `fix.txt` containing "I fixed the code!" and save. Add and commit the change on the new branch.
- Go back to the main branch. Check the content of the directory. Do you see the new file? Why not?
- Merge the `fixCode` branch into main
- Repeat all the above steps (with a different branch name & commit) using the GUI on VSCode (*self-study*)

::: {.callout-tip collapse="true"}
#### Solution
Please complete
:::

<br>


## On merge conflicts
- Create a new branch called `conflictBranch`. Checkout the new branch.
- Change the text in `humorforprogrammers.txt` to "*Code is like humor. When you have to explain it, it’s really really bad.*" and save. Add and commit the change.
- Go back to main and merge `conflictBranch` into main. Resolve the merge conflict and commit the merge.

::: {.callout-tip collapse="true"}
#### Solution
Please complete.

Make sure you are ready to explain how to deal with "forced" commit messages in the terminal (vim or nano) and in the GUI of VSCode.
:::

<br>

## Reference
Learn `git` with [learngitbranching.js.org](https://learngitbranching.js.org/).